nohup: ignoring input
2024-11-15 19:47:26 - INFO - PMTfication starts...
2024-11-15 19:47:26 - INFO - The number of files in the subdirectory: 2
2024-11-15 19:47:26 - INFO - Found 2 database files in subdirectory 99999.
Processing 99999:   0%|          | 0/2 [00:00<?, ?it/s]2024-11-15 19:47:26 - INFO - Starting processing for database file: merged_part_98.db
Processing 99999:   0%|          | 0/2 [00:00<?, ?it/s]
2024-11-15 19:47:27 - ERROR - An error occurred: Float value 1.35 was truncated converting to int32
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 315, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 303, in main
    pmtfier.pmtfy_subdir(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 263, in pmtfy_subdir
    self.pmtfy_db(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 225, in pmtfy_db
    consolidated_df = self._divide_and_conquer_db(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 195, in _divide_and_conquer_db
    shard_df = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 154, in pmtfy_shard
    pa_pmtfied = summariser()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 50, in __call__
    return self._get_PMTfied_pa()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 82, in _get_PMTfied_pa
    return pa.Table.from_pydict(pa_arrays, schema=PMTSummariser._SCHEMA)
  File "pyarrow/table.pxi", line 1920, in pyarrow.lib._Tabular.from_pydict
  File "pyarrow/table.pxi", line 6009, in pyarrow.lib._from_pydict
  File "pyarrow/array.pxi", line 382, in pyarrow.lib.asarray
  File "pyarrow/array.pxi", line 985, in pyarrow.lib.Array.cast
  File "/groups/icecube/cyan/.local/lib/python3.9/site-packages/pyarrow/compute.py", line 404, in cast
    return call_function("cast", [arr], options, memory_pool)
  File "pyarrow/_compute.pyx", line 590, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 385, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Float value 1.35 was truncated converting to int32
