Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PulseMapStatViewer.py", line 384, in <module>
    viewer = PulseMapStatViewer(args.source_db, args.output_pdf)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PulseMapStatViewer.py", line 18, in __init__
    self.df_features = self._convertDBtoDF(source_db, 'SRTInIcePulses')
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PulseMapStatViewer.py", line 23, in _convertDBtoDF
    con = sql.connect(file)
TypeError: expected str, bytes or os.PathLike object, not PulseMapStatViewer
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PulseMapStatViewer.py", line 2, in <module>
    import pandas as pd
  File "/groups/icecube/cyan/.local/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/groups/icecube/cyan/.local/lib/python3.9/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/groups/icecube/cyan/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # isort: skip # type: ignore[reportUnusedImport]
KeyboardInterrupt
