2024-12-10 04:17:20 - INFO - PMTfication by part starts...
2024-12-10 04:17:20 - INFO - Processing file: merged_part_3.db
2024-12-10 04:17:20 - INFO - Using up to 48 workers.
2024-12-10 04:17:40 - INFO - Processing shard 1 of part 3 in subdirectory 0003000-0003999.
2024-12-10 04:29:02 - ERROR - An error occurred: __init__() missing 1 required positional argument: 'event_no_subset'
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 59, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 49, in main
    pmtfier.pmtfy_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 205, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 183, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 163, in pmtfy_shard
    truth_maker = PMTTruthMaker(con_source, source_table, truth_table_name, event_batch)
TypeError: __init__() missing 1 required positional argument: 'event_no_subset'
