2024-11-29 12:39:43 - INFO - PMTfication by part starts...
2024-11-29 12:39:43 - INFO - Processing file: merged_part_1.db
2024-11-29 12:39:43 - INFO - Using up to 32 workers.
2024-11-29 12:40:03 - INFO - Processing shard 1 of part 1 in subdirectory 0003000-0003999.
2024-11-29 12:46:17 - ERROR - An error occurred: invalid literal for int() with base 10: '{signal_or_noise_tag}{subdir_tag:02}{part_no:04}{event_no.as_py():08}'
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 59, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 49, in main
    pmtfier.pmtfy_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 205, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 183, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 157, in pmtfy_shard
    pa_pmtfied = self._add_enhance_event_no(pa_pmtfied, subdir_tag, part_no)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 121, in _add_enhance_event_no
    enhanced_event_no = [
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 122, in <listcomp>
    int("{signal_or_noise_tag}{subdir_tag:02}{part_no:04}{event_no.as_py():08}")
ValueError: invalid literal for int() with base 10: '{signal_or_noise_tag}{subdir_tag:02}{part_no:04}{event_no.as_py():08}'
