2024-11-26 10:38:34 - INFO - PMTfication by part starts...
2024-11-26 10:38:34 - INFO - Processing file: merged_part_13.db
2024-11-26 10:38:34 - INFO - Using up to 5 workers.
2024-11-26 10:38:35 - INFO - Processing shard 1 of part 13 in subdirectory 22012.
2024-11-26 10:42:39 - ERROR - An error occurred: 'PMTSummariser' object has no attribute 'time_scal'
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 57, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 46, in main
    pmtfier.pmtfy_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 205, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 183, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 156, in pmtfy_shard
    pa_pmtfied = summariser()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 87, in __call__
    return self._get_PMTfied_pa()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 106, in _get_PMTfied_pa
    dom_data = self._process_DOM(pulses, avg_dom_position)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 183, in _process_DOM
    first_three_pulse_time = self._get_first_pulse_time(pulses, saturation_status)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 270, in _get_first_pulse_time
    pulse_times = (pulse_times - self.time_shifter) * self.time_scal
AttributeError: 'PMTSummariser' object has no attribute 'time_scal'
