2025-02-13 14:49:55 - INFO - PMTfication by part starts...
2025-02-13 14:49:55 - INFO - Processing file: merged_part_21.db
2025-02-13 14:49:55 - INFO - Using up to 40 workers.
2025-02-13 14:49:56 - INFO - Processing shard 1 of part 21 in subdirectory 22018.
2025-02-13 14:56:56 - ERROR - An error occurred: database or disk is full
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 60, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfy_by_part.py", line 55, in main
    pmtfier.pmtfy_part(source_part_file=source_file_path)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 212, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 190, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 177, in pmtfy_shard
    pa_truth_shard = truth_maker(int(self.subdir_tag), part_no, shard_no, event_batch)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_truth_maker.py", line 132, in __call__
    truth_table = self._get_truth_pa_shard(receipt_pa, event_no_subset)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_truth_maker.py", line 185, in _get_truth_pa_shard
    rows, columns = self._execute_query(truth_query)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_truth_maker.py", line 392, in _execute_query
    cursor.execute(query)
sqlite3.OperationalError: database or disk is full
