Starting job at Sat Feb 15 12:13:51 PM CET 2025
Running Filter_by_part.py for subdirectory 22018, part 19
2025-02-15 12:13:51 - INFO - Event filtering process starts...
2025-02-15 12:13:51 - INFO - Initialized PureNeutrinoEventFilter filter for 22018/19
2025-02-15 12:13:51 - INFO - Loaded 18 event specifier files from /lustre/hpc/project/icecube/HE_Nu_Aske_Oct2024/clean_events_dict/22018/22018/reduced
2025-02-15 12:13:51 - ERROR - An error occurred: 'Field "RunID" does not exist in schema'
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/Filter_by_part.py", line 65, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/Filter_by_part.py", line 61, in main
    run()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/Filter_by_part.py", line 48, in run
    filter_manager = EventFilterManager(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/EventFilterManager.py", line 18, in __init__
    self.filter_instances = self._instantiate_filters() # dict[str, EventFilter]
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/EventFilterManager.py", line 69, in _instantiate_filters
    filter_instances[alias] = filter_class(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/PureNeutrinoEventFilter.py", line 15, in __init__
    super().__init__(source_subdir=source_subdir,
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/EventFilter.py", line 27, in __init__
    self._set_valid_event_nos()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/EventFilter.py", line 122, in wrapper
    return method(*args, **kwargs)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/PureNeutrinoEventFilter.py", line 23, in _set_valid_event_nos
    relevant_csvs = self._get_relevant_csv_files(truth_table)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/Selection/PureNeutrinoEventFilter.py", line 49, in _get_relevant_csv_files
    run_ids = truth_table.column("RunID").to_pylist()
  File "pyarrow/table.pxi", line 1779, in pyarrow.lib._Tabular.column
  File "pyarrow/table.pxi", line 1715, in pyarrow.lib._Tabular._ensure_integer_index
KeyError: 'Field "RunID" does not exist in schema'
Job completed at Sat Feb 15 12:13:51 PM CET 2025
